# application.yml 
--- 


# MESSAGING 
asw.kafka.channel.in: asw.kafka.channel.alpha
asw.kafka.groupid: simple-consumer

spring: 
  application: 
    name: bservice
  kafka:
    consumer:
      bootstrap-servers: ${DOCKER_HOST_IP:10.11.1.111}:9092
      group-id: ${asw.kafka.groupid}
      auto-offset-reset: earliest
      # auto-offset-reset: latest
      # key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      #CISTAVA properties.spring.json.trusted.packages: *
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eureka:8761/eureka/
  instance: 
    leaseRenewalIntervalInSeconds: 10
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
server: 
  port: ${PORT:${SERVER_PORT:0}}
  #8080    
names: Azzonzo, Azzeni, Ascanio, Ariel, Afaccrucazz