version: '3'
services:
  eureka:
    build: 
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
  aservice:
    build: 
      context: ./a-service
    depends_on:
      - "eureka"
  bservice:
    build: 
      context: ./b-service
    depends_on:
      - "eureka"
  cservice:
    build: 
      context: ./c-service
    depends_on:
      - "eureka"
  zuul:
    build: 
      context: ./zuul-gateway
    container_name: zuul
    ports:
    - "8080:8080"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-10.11.1.111}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "asw.kafka.channel.alpha:4:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
