# application.yml
--- 
spring: 
  application: 
    name: cservice
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eureka:8761/eureka/
  instance: 
    leaseRenewalIntervalInSeconds: 10
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
server: 
  port: ${PORT:${SERVER_PORT:0}}

names: Mario, Luigi, Yoshi, Peach, Wario