# application.yml 
--- 

# MESSAGING 
asw.kafka.channel.out: asw.kafka.channel.alpha

spring: 
  application: 
    name: aservice
  kafka:
    bootstrap-servers: ${DOCKER_HOST_IP:10.11.1.111}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eureka:8761/eureka/
  instance: 
    leaseRenewalIntervalInSeconds: 10
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
server: 
  port: ${PORT:${SERVER_PORT:0}}

names: Alice, Carlo, Alberto, Max, Marco
animals: Orso, Lupo, Cane, Gatto, Coniglio