# application.yml 
--- 
spring: 
  application: 
    name: aservice
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eureka:8761/eureka/
  instance: 
    leaseRenewalIntervalInSeconds: 10
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
server: 
  port: 8080

names: Alice, Carlo, Alberto, Max, Marco
animals: Orso, Lupo, Cane, Gatto, Coniglio